packages:
    github.com/itmrchow/todolist-users/internal/repository:
        config:
            filename: "{{.InterfaceNameSnake}}_mock.go"
            dir: "{{.InterfaceDir}}"

        interfaces:
            UsersRepository:
        
