# server
SERVER_NAME: todolist-user
SERVER_PORT: 50051

# mysql
MYSQL_URL_SUFFIX: 
MYSQL_DB_ACCOUNT: 
MYSQL_DB_PASSWORD: 
MYSQL_DB_HOST: 
MYSQL_DB_PORT: 
MYSQL_DB_NAME: 

# jwt
JWT_SECRET_KEY: 
JWT_EXPIRE_AT: 8
 